spring:
  jpa:
    properties:
      hibernate.hibernate.default_batch_fetch_size: 100
    open-in-view: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB

---
spring.config.activate.on-profile: local
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:core;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  servlet:
    multipart:
      location: D:\\down\\TMP\\image\\image
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true  #data.sql ??? ??? DB? ???? ? ??? ????? ??
  h2:
    console:
      enabled: true # /h2-console ??

---
spring.config.activate.on-profile: dev
spring:
  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 5
      keepalive-time: 30000
      validation-timeout: 1000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${database.name}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${database.username}
    password: ${database.password}
  servlet:
    multipart:
      location: /Users/chany/Desktop/image
  sql: # mysql??? data.sql? ??? ????? ?????.
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    defer-datasource-initialization: true #data.sql ??? ??? DB? ???? ? ??? ????? ??

springdoc:
  swagger-ui:
    enabled:true

---
spring.config.activate.on-profile: prod
spring:
  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 5
      keepalive-time: 30000
      validation-timeout: 1000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${database.name}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${database.username}
    password: ${database.password}
  servlet:
    multipart:
      location: /srv/upload-files
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true






