spring:
  jpa:
    properties:
      hibernate.hibernate.default_batch_fetch_size: 100
    open-in-view: false
    hibernate:
      ddl-auto: none
  config:
    import: classpath:application-api-key.yml

springdoc:
  swagger-ui:
    enabled: true
    path: /api-docs
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    enabled: true

logging:
  config: classpath:logback-${spring.profiles.active}.xml

---
spring.config.activate.on-profile: local
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:core;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true  #data.sql 파일의 실행이 DB가 연결되고 난 이후에 실행되도록 설정
  h2:
    console:
      enabled: true # /h2-console 설정
app:
  base-url: "http://localhost:5173"
  base-api-url: "http://localhost:8080"
  secure-cookie: false
---
spring.config.import: classpath:application-db.yml
spring.config.activate.on-profile: dev
spring:
  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 5
      keepalive-time: 30000
      validation-timeout: 1000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${database.dev.ip}/${database.dev.name}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${database.dev.username}
    password: ${database.dev.password}
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  sql.init.mode: never

springdoc:
  swagger-ui:
    enabled:true

app:
  base-url: "http://localhost:5173"
  base-api-url: "http://localhost:8080"
  secure-cookie: false

---
spring.config.import: classpath:application-db.yml
spring.config.activate.on-profile: prod
spring:
  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 5
      keepalive-time: 30000
      validation-timeout: 1000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${database.prod.name}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${database.prod.username}
    password: ${database.prod.password}
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  sql.init.mode: never

app:
  base-url: "https://nagne.site"
  base-api-url: "https://api.nagne.site"
  secure-cookie: true

logging:
  discord:
    webhook-uri-prod: ${DISCORD_WEBHOOK_PROD_URL}


